lyceum/about/urls.py
from django.urls import path

import about.views


app_name = "about"

urlpatterns = [
    path("", about.views.description, name="about"),
]

lyceum/homepage/urls.py
from django.urls import path

import homepage.views

app_name = "homepage"

urlpatterns = [
    path("", homepage.views.home, name="home"),
    path("coffee/", homepage.views.coffee_response, name="coffee"),
    path("echo/", homepage.views.echo, name="echo"),
    path("echo/submit/", homepage.views.echo_submit, name="echo_submit"),
]

lyceum/lyceum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
import django.contrib.auth.urls
from django.urls import include, path


urlpatterns = [
    path("", include("homepage.urls")),
    path("catalog/", include("catalog.urls")),
    path("about/", include("about.urls")),
    path("feedback/", include("feedback.urls")),
    path("auth/", include("users.urls")),
    path("auth/", include(django.contrib.auth.urls)),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATICFILES_DIRS,
    )

lyceum/users/urls.py
from django.contrib import auth
from django.urls import path

import users.views

app_name = "users"

urlpatterns = [
    path(
        "login/",
        auth.views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path("logout/", auth.views.LogoutView.as_view(), name="logout"),
    path(
        "password_change/",
        auth.views.PasswordChangeView.as_view(
            template_name="users/password_change.html",
        ),
        name="password_change",
    ),
    path(
        "password_change/done/",
        auth.views.PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html",
        ),
        name="password_change_done",
    ),
    path(
        "password_reset/",
        auth.views.PasswordResetView.as_view(
            template_name="users/password_reset.html",
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth.views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth.views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth.views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
    path("signup/", users.views.signup, name="signup"),
    path("activate/<str:username>/", users.views.activate, name="activate"),
    path("users/", users.views.user_list, name="user_list"),
    path("users/<int:pk>/", users.views.user_detail, name="user_detail"),
    path("profile/", users.views.profile, name="profile"),
]

lyceum/users/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

__all__ = ["Profile", "PersonManager", "Person"]


class PersonManager(models.Manager):
    def active_users_list(self):
        return self.filter(
            is_active=True,
        ).only(
            "username",
        )

    def queryset_for_user_detail(self):
        return self.only("email", "first_name", "last_name").select_related(
            User.profile.related.name,
        )


class Person(User):
    objects = PersonManager()

    class Meta:
        proxy = True


class Profile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name="profile",
    )
    birthday = models.DateField(null=True, blank=True)
    image = models.ImageField(upload_to="users/", null=True, blank=True)
    coffe_count = models.IntegerField(default=0)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

lyceum/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from users.models import Profile

__all__ = ["RegisterForm", "UserForm", "ProfileForm"]


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]


class UserForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs["class"] = "form-control"

    class Meta:
        model = User
        fields = ["email", "first_name"]
        labels = {
            "email": "Почта",
            "first_name": "Имя",
        }


class ProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs["class"] = "form-control"

    class Meta:
        model = Profile
        fields = ["birthday", "image"]
        labels = {
            "birthday": "День рождения",
            "Картинка": "image",
        }

lyceum/users/views.py
from django.conf import settings
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone

from users.forms import ProfileForm, RegisterForm, UserForm
from users.models import Person

__all__ = ["signup"]


def signup(request):
    template = "users/signup.html"
    form = RegisterForm(request.POST or None)
    if request.method == "POST" and form.is_valid():
        username = form.cleaned_data["username"]
        reg_url = f"http://127.0.0.1:8000/auth/activate/{username}"
        send_mail(
            f"Привет {username}",
            f"Для активации ползователя перейдите по ссылке:\n{reg_url}",
            settings.FEEDBACK_SENDER,
            [form.cleaned_data["email"]],
            fail_silently=False,
        )
        user = form.save(commit=False)
        user.is_active = settings.DEFAULT_USER_IS_ACTIVE
        user.save()
        return redirect("users:login")
    context = {"form": form}
    return render(request, template, context)


def activate(request, username):
    user = User.objects.get(username=username)
    now = timezone.now()
    reg_datetime = user.date_joined
    print(reg_datetime)
    time = now - reg_datetime
    if 12 * 60 * 60 > time.total_seconds():
        user.is_active = True
        user.save()
        text = f"Вы активировали аккаунт {username}"
    else:
        text = "Истек срок активации (12 часов)"

    template = "users/activate.html"
    context = {"text": text}
    return render(request, template, context)


def user_list(request):
    template = "users/user_list.html"
    users = Person.objects.active_users_list()
    context = {"users": users}
    return render(request, template, context)


def user_detail(request, pk):
    template = "users/user_detail.html"
    queryset = Person.objects.queryset_for_user_detail()
    user = get_object_or_404(queryset, pk=pk)
    context = {"user": user}
    return render(request, template, context)


def profile(request):
    user = request.user
    template = "users/profile.html"
    initial_user = {
        "email": user.email,
        "first_name": user.first_name,
    }
    form_user = UserForm(request.POST or initial_user)
    form_profile = ProfileForm(request.POST, request.FILES)
    if (
        request.method == "POST"
        and form_user.is_valid()
        and form_profile.is_valid()
    ):
        user.email = form_user.cleaned_data["email"]
        user.first_name = form_user.cleaned_data["first_name"]
        user.profile.birthday = form_profile.cleaned_data["birthday"]
        user.profile.image = form_profile.cleaned_data["image"]
        user.save()
        user.profile.save()
        return redirect("users:profile")

    initial_profile = {
        "birthday": user.profile.birthday,
        "image": user.profile.image.url,
    }
    form_profile = ProfileForm(initial_profile)
    context = {"form_user": form_user, "form_profile": form_profile}
    return render(request, template, context)

lyceum/templates/users/activate.html
{% extends "base.html" %}
{% block content %}
  <p>{{ text }}</p>
{% endblock content %}

lyceum/templates/users/login.html
{% extends "base.html" %}
{% block content %}
  <h1>Вход</h1>
  {% if form.errors %}
    {% for field in form %}
      {% for error in field.errors %}
        {{ error|escape }}
      {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
      {{ error|escape }}
    {% endfor %}
  {% endif %}
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <div class="form-group" style="margin-top: 15px;">
        <label for="{{ field.id_for_label }}">
          {{ field.label }}
        </label>
        {% load filters %}
        {{ field|add_class:"form-control" }}
        {% if field.help_text %}
          <small class="text-muted">
            {{ field.help_text|safe }}
          </small>
        {% endif %}
      </div>
    {% endfor %}
    <div style="margin-top: 20px; width: 100%; display: flex; justify-content: space-between">
      <button type="submit" class="btn btn-primary">
        Войти
      </button>
      <a href="{% url 'users:password_reset' %}" style="text-align: left;">
        Забыли пароль?
      </a>
    </div>
  </form>
{% endblock content %}

lyceum/templates/users/password_change.html
{% extends "base.html" %}
{% block content %}
  <h1>Изменение пароля</h1>
  {% if form.errors %}
    {% for field in form %}
      {% for error in field.errors %}
        {{ error|escape }}
      {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
      {{ error|escape }}
    {% endfor %}
  {% endif %}
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <div class="form-group" style="margin-top: 15px;">
        <label for="{{ field.id_for_label }}">
          {{ field.label }}
        </label>
        {% load filters %}
        {{ field|add_class:"form-control" }}
      </div>
    {% endfor %}
    <div style="margin-top: 20px; width: 100%;">
      <button type="submit" class="btn btn-primary">
        Изменить пароль
      </button>
    </div>
  </form>
{% endblock content %}

lyceum/templates/users/password_change_done.html
{% extends "base.html" %}
{% block content %}
  <h1>Ваш пароль успешно изменён</h1>
{% endblock content %}

lyceum/templates/users/password_reset.html
{% extends "base.html" %}
{% block content %}
  <h1>Востановление пароля</h1>
  <p>
    Забыли пароль? Введите свой адрес электронной почты ниже, и мы вышлем вам инструкцию, как установить новый пароль.
  </p>
  {% if form.errors %}
    {% for field in form %}
      {% for error in field.errors %}
        {{ error|escape }}
      {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
      {{ error|escape }}
    {% endfor %}
  {% endif %}
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <div class="form-group" style="margin-top: 15px;">
        <label for="{{ field.id_for_label }}">
          {{ field.label }}
        </label>
        {% load filters %}
        {{ field|add_class:"form-control" }}
      </div>
    {% endfor %}
    <div style="margin-top: 20px; width: 100%;">
      <button type="submit" class="btn btn-primary">
        Востановить пароль
      </button>
    </div>
  </form>
{% endblock content %}

lyceum/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block content %}
  <h1>Восстановление пароля завершено</h1>
  <p>
    Ваш пароль был сохранен. Теперь вы можете войти.
  </p>
  <a href="{% url 'users:login' %}">Войти</a>
{% endblock content %}

lyceum/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% block content %}
  <h1>Востановление пароля</h1>
  <p>
    Пожалуйста, введите новый пароль дважды.
  </p>
  {% if form.errors %}
    {% for field in form %}
      {% for error in field.errors %}
        {{ error|escape }}
      {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
      {{ error|escape }}
    {% endfor %}
  {% endif %}
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <div class="form-group" style="margin-top: 15px;">
        <label for="{{ field.id_for_label }}">
          {{ field.label }}
        </label>
        {% load filters %}
        {{ field|add_class:"form-control" }}
      </div>
    {% endfor %}
    <div style="margin-top: 20px; width: 100%;">
      <button type="submit" class="btn btn-primary">
        Изменить пароль
      </button>
    </div>
  </form>
{% endblock content %}

lyceum/templates/users/password_reset_done.html
{% extends "base.html" %}
{% block content %}
  <h1>Письмо с инструкциями по восстановлению пароля отправлено</h1>
  <p>
    Мы отправили вам инструкцию по установке нового пароля на указанный адрес электронной почты (если в нашей базе данных есть такой адрес). Вы должны получить ее в ближайшее время.
  </p>
  <p>
    Если вы не получили письмо, пожалуйста, убедитесь, что вы ввели адрес с которым Вы зарегистрировались, и проверьте папку со спамом.
  </p>
{% endblock content %}

lyceum/templates/users/profile.html
{% extends "base.html" %}
{% block content %}
  {% if form.errors %}
    {% for field in form %}
      {% for error in field.errors %}
        {{ error|escape }}
      {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
      {{ error|escape }}
    {% endfor %}
  {% endif %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form_user %}
      <div class="form-group">
        {{ field.label_tag}} {{field}}
        {% if field.help_text %}
        <small class="text-muted">{{ field.help_text|safe }}</small>
        {% endif %}
      </div>
    {% endfor %}
    {% load static %}
    {% for field in form_profile %}
      <div class="form-group">
        {{ field.label_tag}} {{field}}
        {% if field.help_text %}
        <small class="text-muted">{{ field.help_text|safe }}</small>
        {% endif %}
      </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary" style="margin-top: 20px;">Сохранить</button>
  </form>
  <a href="{% url 'homepage:coffee' %}">Выпить кофе</a>
{% endblock content %}

lyceum/templates/users/signup.html
{% extends "base.html" %}
{% block content %}
  <h1>Регистрация</h1>
  {% if form.errors %}
    {% for field in form %}
      {% for error in field.errors %}
        {{ error|escape }}
      {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
      {{ error|escape }}
    {% endfor %}
  {% endif %}
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <div class="form-group" style="margin-top: 15px;">
        <label for="{{ field.id_for_label }}">
          {{ field.label }}
        </label>
        {% load filters %}
        {{ field|add_class:"form-control" }}
      </div>
    {% endfor %}
    <div style="margin-top: 20px; width: 100%; display: flex; justify-content: space-between">
      <button type="submit" class="btn btn-primary">
        Зарегестрироваться
      </button>
      <a href="{% url 'users:login' %}" style="text-align: left;">
        Войти
      </a>
    </div>
  </form>
{% endblock content %}

lyceum/templates/users/user_detail.html
{% extends "base.html" %}
{% block content %}
  <div>Почта: {{ user.email }}</div>
  <div>Имя: {% if user.first_name %}{{ user.first_name }}{% else %}<span style="color: red;">неуказано</span>{% endif %}</div>
  <div>Фамилия: {% if user.last_name %}{{ user.last_name }}{% else %}<span style="color: red;">неуказано</span>{% endif %}</div>
  <div>Дата рождения: {% if user.profile.birthday %}{{ user.profile.birthday }}{% else %}<span style="color: red;">неуказано</span>{% endif %}</div>
  <div>Картинка: {% if user.profile.image %}<img src="{{ user.profile.image.url }}" width=300px>{% else %}<span style="color: red;">неуказано</span>{% endif %}</div>
  <div>Количество выпитого кофе: {{ user.profile.coffe_count }}</div>
{% endblock content %}

lyceum/templates/users/user_list.html
{% extends "base.html" %}
{% block content %}
  {% for user in users %}
    <a href="{% url 'users:user_detail' user.pk %}">{{ user.username }}</a>
  {% endfor %}
{% endblock content %}