lyceum/about/urls.py
from django.urls import path

import about.views


app_name = "about"

urlpatterns = [
    path("", about.views.description, name="about"),
]

lyceum/catalog/urls.py
from django.urls import path

import catalog.views

app_name = "catalog"

urlpatterns = [
    path("", catalog.views.item_list, name="item_list"),
    path("<int:pk>/", catalog.views.item_detail, name="item_detail"),
]

lyceum/feedback/urls.py
from django.urls import path

import feedback.views

app_name = "feedback"

urlpatterns = [
    path("", feedback.views.feedback, name="feedback"),
]

lyceum/homepage/urls.py
from django.urls import path

import homepage.views

app_name = "homepage"

urlpatterns = [
    path("", homepage.views.home, name="home"),
    path("coffee/", homepage.views.coffee_response, name="coffee"),
    path("echo/", homepage.views.echo, name="echo"),
    path("echo/submit/", homepage.views.echo_submit, name="echo_submit"),
]

lyceum/lyceum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
import django.contrib.auth.urls
from django.urls import include, path


urlpatterns = [
    path("", include("homepage.urls")),
    path("catalog/", include("catalog.urls")),
    path("about/", include("about.urls")),
    path("feedback/", include("feedback.urls")),
    path("auth/", include("users.urls")),
    path("auth/", include(django.contrib.auth.urls)),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATICFILES_DIRS,
    )

lyceum/templates/includes/footer.html
<div class="container">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
      <div class="col-md-4 d-flex align-items-center">
        <span class="text-muted">Web-Разработка 2023</span>
      </div>
    </footer>
  </div>

lyceum/templates/includes/header.html
<div class="container">
  <header class="p-3 mb-3 border-bottom">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
        {% load static %}
        <img src="{% static 'img/efremov.jpg' %}" class="bi me-2" width="40" height="32" role="img" aria-label="Nikitin Efrema">
      </a>

      
      {% with request.resolver_match.view_name as view_name %}
      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><a href="{% url 'homepage:home' %}" class="nav-link px-2 {% if view_name == 'homepage:home' %}active{% else  %}link-dark{% endif %}">Главная</a></li>
        <li><a href="{% url 'catalog:item_list' %}" class="nav-link px-2 {% if view_name == 'catalog:item_list' %}active{% else  %}link-dark{% endif %}">Список товаров</a></li>
        <li><a href="{% url 'about:about' %}" class="nav-link px-2 {% if view_name == 'about:about' %}active{% else  %}link-dark{% endif %}">О проекте</a></li>
        <li><a href="{% url 'feedback:feedback' %}" class="nav-link px-2 {% if view_name == 'feedback:feedback' %}active{% else  %}link-dark{% endif %}">Форма связи</a></li>
      </ul>
      {% endwith %}
    </div>
  </header>
</div>

lyceum/templates/includes/item_card.html
<div class="card" style="width: 18rem;">
    <div class="card-body">
        <a href="{% url 'catalog:item_detail' item.pk %}"><h5 class="card-title">{{ item.name }}</h5></a>
        <h6 class="card-subtitle mb-2 text-muted">{{ item.category }}</h6>
        <p class="card-text">{{ item.text|truncatewords_html:10|safe }}</p>
        {% for tag in item.tags.all %}
        <a href="#" class="card-link">{{ tag }}</a>
        {% endfor %}
    </div>
</div>