lyceum/about/urls.py
from django.urls import path

import about.views


app_name = "about"

urlpatterns = [
    path("", about.views.description, name="about"),
]

lyceum/catalog/urls.py
from django.urls import path

import catalog.views

app_name = "catalog"

urlpatterns = [
    path("", catalog.views.item_list, name="item_list"),
    path("<int:pk>/", catalog.views.item_detail, name="item_detail"),
]

lyceum/homepage/urls.py
from django.urls import path

import homepage.views

app_name = "homepage"

urlpatterns = [
    path("", homepage.views.home, name="home"),
    path("coffee/", homepage.views.coffee_response, name="coffee"),
    path("echo/", homepage.views.echo, name="echo"),
    path("echo/submit/", homepage.views.echo_submit, name="echo_submit"),
]

lyceum/lyceum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
import django.contrib.auth.urls
from django.urls import include, path


urlpatterns = [
    path("", include("homepage.urls")),
    path("catalog/", include("catalog.urls")),
    path("about/", include("about.urls")),
    path("feedback/", include("feedback.urls")),
    path("auth/", include("users.urls")),
    path("auth/", include(django.contrib.auth.urls)),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATICFILES_DIRS,
    )

lyceum/homepage/forms.py
from django import forms

__all__ = ["EchoForm"]


class EchoForm(forms.Form):
    text = forms.CharField(
        widget=forms.Textarea(attrs={"class": "form-control", "rows": 3}),
    )

lyceum/homepage/views.py
from django.http import HttpResponse, HttpResponseNotAllowed
from django.shortcuts import render

import catalog.models
from homepage.forms import EchoForm


__all__ = ["coffee_response", "home"]


def home(request):
    items = catalog.models.Item.objects.on_main()
    template = "homepage/main.html"
    context = {"items": items}
    return render(request, template, context)


def coffee_response(request):
    user = request.user
    if user.is_authenticated:
        user.profile.coffe_count += 1
        user.save()
    return HttpResponse("Я чайник", status=418)


def echo(request):
    if request.method == "GET":
        form = EchoForm()
        context = {"form": form}
        template = "homepage/echo.html"
        return render(request, template, context)
    return HttpResponseNotAllowed(["POST"])


def echo_submit(request):
    if request.method == "POST":
        form = EchoForm(request.POST or None)
        if form.is_valid():
            text = form.cleaned_data.get("text")
            return HttpResponse(text)
    return HttpResponseNotAllowed(["GET"])

lyceum/templates/homepage/echo.html
{% extends "base.html" %}
{% block content %}
  <form action={% url "homepage:echo_submit" %} method="post">
    {% csrf_token %}
    {% for field in form %}
        <div class="form-group">
        {{ field.label_tag}} {{field}}
        {% if field.help_text %}
        <small class="text-muted">{{ field.help_text|safe }}</small>
        {% endif %}
        </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary" style="margin-top: 20px;">Отправить форму</button>
  </form>
{% endblock content %}

lyceum/templates/homepage/main.html
{% extends "base.html" %}
{% block content %}
  <h1>Скорее переходи в список товаров и покупай</h1>
  {% load static %}
  <div class="row">
    {% for item in items %}
      <div class="col">
        <a  href="{% url 'catalog:item_detail' item.id %}" style="text-decoration:none;">
        {% include "includes/item_card.html" %}
        </a>
      </div>
    {% endfor %}
  </div>
{% endblock content %}